# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  baget:
    image: baget
    build:
      context: .
      dockerfile: src/BaGet/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
